
##################################################################
# Disabled Rules
##################################################################
disabled_rules: # rule identifiers to exclude from running
#  - identifier_name # cant be setted to warning
  - shorthand_operator
  - explicit_type_interface

##################################################################
# Excluded directories
##################################################################
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Example/Pods
  - Pods
  - Carthage
  - fastlane

##################################################################
# Rules Forced
##################################################################
opt_in_rules: # some rules are only opt-in
  - anyobject_protocol
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - explicit_type_interface
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
# - file_header
# - file_name
  - first_where
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_parameters
  - nimble_operator
  - no_fallthrough_only
#  - no_grouping_extension
  - operator_usage_whitespace
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - redundant_nil_coalescing
  - required_enum_case
  - single_test_class
  - sorted_imports
  - sorted_first_last
  - static_operator
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - vertical_parameter_alignment_on_call
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
  - unused_private_declaration

anyobject_protocol:
  severity: error
array_init:
  severity: error
attributes:
  severity: error
block_based_kvo:
  severity: error
class_delegate_protocol:
  severity: error
closure_body_length:
  severity: warning
closure_spacing:
  severity: error
closure_end_indentation:
  severity: error
collection_alignment:
  severity: error
colon:
  severity: error
comma:
  severity: error
compiler_protocol_init:
  severity: error
conditional_returns_on_newline:
  severity: warning
contains_over_first_not_nil:
  severity: warning
control_statement:
  severity: error
convenience_type:
  severity: warning
cyclomatic_complexity:
  severity: error
discarded_notification_center_observer:
  severity: error
discouraged_direct_init:
  severity: error
discouraged_object_literal:
  severity: error
discouraged_optional_boolean:
  severity: warning
discouraged_optional_collection:
  severity: error
dynamic_inline:
  severity: warning
empty_count:
  severity: error
empty_string:
  severity: error
empty_xctest_method:
  severity: error
explicit_init:
  severity: warning
explicit_type_interface:
  severity: warning
extension_access_modifier:
  severity: warning
fallthrough:
  severity: warning
fatal_error_message:
  severity: warning
#file_header:
#  severity: warning
# file_name:
#   severity: warning
first_where:
  severity: warning
function_body_length:
  warning: 130
  error: 300
function_default_parameter_at_end:
  severity: warning
identical_operands:
  severity: error
implicit_return:
  severity: warning
implicitly_unwrapped_optional:
  severity: warning
inert_defer:
  severity: error
joined_default_parameter:
  severity: warning
legacy_random:
  severity: warning
let_var_whitespace:
  severity: warning
line_length:
  warning: 120
  error: 500
literal_expression_end_indentation:
  severity: warning
missing_docs:
  severity: warning
modifier_order:
  severity: warning
multiline_arguments:
  severity: warning
multiline_arguments_brackets:
  severity: warning
multiline_function_chains:
  severity: warning
multiline_parameters:
  severity: warning
nimble_operator:
  severity: warning
notification_center_detachment:
  severity: warning
no_fallthrough_only:
  severity: warning
no_grouping_extension:
  severity: warning
operator_whitespace:
  severity: error
overridden_super_call:
  severity: error
pattern_matching_keywords:
  severity: warning
prefixed_toplevel_constant:
  severity: warning
private_action:
  severity: error
private_outlet:
  severity: error
prohibited_super_call:
  severity: error
quick_discouraged_call:
  severity: error
quick_discouraged_focused_test:
  severity: error
quick_discouraged_pending_test:
  severity: error
redundant_nil_coalescing:
  severity: warning
redundant_string_enum_value:
  severity: error
required_enum_case:
  severity: warning
single_test_class:
  severity: warning
sorted_imports:
  severity: warning
sorted_first_last:
  severity: warning
static_operator:
  severity: warning
strict_fileprivate:
  severity: warning
switch_case_on_newline:
  severity: warning
syntactic_sugar:
  severity: error
type_name:
  min_length: 2
  max_length: 55
unneeded_break_in_switch:
  severity: error
unused_import:
  severity: error
unused_private_declaration:
  severity: error
toggle_bool:
  severity: warning
trailing_closure:
  severity: warning
type_body_length:
  error: 1000 #bajarlo a 80
unavailable_function:
  severity: warning
unneeded_parentheses_in_closure_argument:
  severity: warning
untyped_error_in_catch:
  severity: warning
unused_import:
  severity: warning
unused_private_declaration:
  severity: warning
vertical_parameter_alignment_on_call:
  severity: warning
xctfail_message:
  severity: error
yoda_condition:
  severity: error
##################################################################
# Private Rules
##################################################################
custom_rules:
  localized_not_NSLocalized: # rule identifier
    included: ".*\\.swift" # regex that defines paths to include during linting. optional.
    name: ".localized instead of NSLocalized" # rule name. optional.
    regex: "(NSLocalizedString)" # matching pattern
    message: "Use .localized instead of NSLocalized" # violation message. optional.
    severity: warning
